INSERT INTO EMPLOYEE (empNum,lastName,firstName,gender,birthDate,hireDate) 
	VALUES (1,'CHEN','David', 'M', CURRENT_DATE, CURRENT_DATE);
INSERT INTO EMPLOYEE (empNum,lastName,firstName,gender,birthDate,hireDate) 
	VALUES (2,'Thomas','Jay', 'M', CURRENT_DATE, CURRENT_DATE);
INSERT INTO EMPLOYEE (empNum,lastName,firstName,gender,birthDate,hireDate) 
	VALUES (3,'Mith','Scott', 'M', CURRENT_DATE, CURRENT_DATE);
INSERT INTO EMPLOYEE (empNum,lastName,firstName,gender,birthDate,hireDate) 
	VALUES (4,'Smith','Car', 'M', CURRENT_DATE, CURRENT_DATE);
	
INSERT INTO AGENT (AGENT_ID, LASTNAME, FIRSTNAME, MIDDLENAME, START_DATE) VALUES (nextval('SEQ_AGT_ID'),'Smith','Car', 'M', CURRENT_DATE);
INSERT INTO AGENT (AGENT_ID, LASTNAME, FIRSTNAME, MIDDLENAME, START_DATE) VALUES (nextval('SEQ_AGT_ID'), 'CHEN','David', CURRENT_DATE);
INSERT INTO AGENT (AGENT_ID, LASTNAME, FIRSTNAME, MIDDLENAME, START_DATE) VALUES (nextval('SEQ_AGT_ID'),'Thomas','Jay', 'M', CURRENT_DATE);
INSERT INTO AGENT (AGENT_ID, LASTNAME, FIRSTNAME, MIDDLENAME, START_DATE) VALUES (nextval('SEQ_AGT_ID'), 'Mith','Scott', CURRENT_DATE);

INSERT INTO R_ACCESSOR VALUES ('10');
INSERT INTO R_ACCESSOR VALUES('11');
INSERT INTO R_ACCESSOR VALUES('12');
INSERT INTO R_ACCESSOR VALUES('13');
INSERT INTO R_ACCESSOR VALUES('14');
INSERT INTO R_ACCESSOR VALUES('15');
INSERT INTO R_ACCESSOR VALUES('16');
INSERT INTO R_ACCESSOR VALUES('17');
INSERT INTO R_ACCESSOR VALUES('18');
INSERT INTO R_ACCESSOR VALUES('19');
INSERT INTO R_ACCESSOR VALUES('20');

INSERT INTO R_ACL VALUES ('1', null);
	INSERT INTO R_ACL VALUES ('11', '1');
	INSERT INTO R_ACL VALUES ('12', '1');
	INSERT INTO R_ACL VALUES ('13', '1');
	INSERT INTO R_ACL VALUES ('14', '1');
INSERT INTO R_ACL VALUES ('2', null);
	INSERT INTO R_ACL VALUES ('21', '2');
	INSERT INTO R_ACL VALUES ('22', '2');
INSERT INTO R_ACL VALUES ('3', null);
	INSERT INTO R_ACL VALUES ('31', '3');
	INSERT INTO R_ACL VALUES ('32', '3');
	INSERT INTO R_ACL VALUES ('33', '3');
	INSERT INTO R_ACL VALUES ('34', '3');
INSERT INTO R_ACL VALUES ('4', null);
	INSERT INTO R_ACL VALUES ('41', '4');
	INSERT INTO R_ACL VALUES ('42', '4');
	INSERT INTO R_ACL VALUES ('43', '4');
	INSERT INTO R_ACL VALUES ('44', '4');
	
INSERT INTO R_ACLDETL (C_ACL, C_ACCESSOR, C_MODE) VALUES ('11', '10', 1);
INSERT INTO R_ACLDETL (C_ACL, C_ACCESSOR, C_MODE) VALUES ('11', '11', 1);
INSERT INTO R_ACLDETL (C_ACL, C_ACCESSOR, C_MODE) VALUES ('11', '12', 1);
INSERT INTO R_ACLDETL (C_ACL, C_ACCESSOR, C_MODE) VALUES ('11', '13', 1);
INSERT INTO R_ACLDETL (C_ACL, C_ACCESSOR, C_MODE) VALUES ('11', '14', 1);


INSERT INTO R_ACLDETL (C_ACL, C_ACCESSOR, C_MODE) VALUES ('12', '10', 2);
INSERT INTO R_ACLDETL (C_ACL, C_ACCESSOR, C_MODE) VALUES ('12', '11', 2);
INSERT INTO R_ACLDETL (C_ACL, C_ACCESSOR, C_MODE) VALUES ('12', '12', 2);
INSERT INTO R_ACLDETL (C_ACL, C_ACCESSOR, C_MODE) VALUES ('12', '13', 2);
INSERT INTO R_ACLDETL (C_ACL, C_ACCESSOR, C_MODE) VALUES ('12', '14', 2);


INSERT INTO R_ACLDETL (C_ACL, C_ACCESSOR, C_MODE) VALUES ('13', '15', 4);
INSERT INTO R_ACLDETL (C_ACL, C_ACCESSOR, C_MODE) VALUES ('13', '11', 4);
INSERT INTO R_ACLDETL (C_ACL, C_ACCESSOR, C_MODE) VALUES ('13', '12', 4);
INSERT INTO R_ACLDETL (C_ACL, C_ACCESSOR, C_MODE) VALUES ('13', '13', 4);
INSERT INTO R_ACLDETL (C_ACL, C_ACCESSOR, C_MODE) VALUES ('13', '14', 4);
